### PR TITLE
Improving wallselect 🔮

### PR DESCRIPTION
**Pull request by PharmaRacist**

### CODE REVIEW

**Comment by PharmaRacist** [comment]
while deep testing found that its very very memory consuming where i have over 600 wallpapers memory usage can go up to 8gb!! to cache all wallpapers so i think it will wait some time

**Comment by PharmaRacist** [comment]
so i have spent the last hour missing with chatgpt since im not programmer i dont code n  js/ts to fnd a better way i think it will be solved by using imagemagick to produce 200x200 thumbnail in the cache folder to be shown this will reduce the memory usage tbh no one uses 600+ wallpapers except me 👉👈 but i hope you could help me to find better mechanism 🤍

**Comment by sh1zicus** [comment]
I can't scroll list in your version.

**Comment by sh1zicus** [comment]
can do without previews at all, only display titles, but it will not be so beautiful

I'll try to do some image compression

**Comment by sh1zicus** [comment]
``` javascript
import Widget from "resource:///com/github/Aylur/ags/widget.js";
import * as Utils from "resource:///com/github/Aylur/ags/utils.js";
import App from "resource:///com/github/Aylur/ags/app.js";
const { GLib } = imports.gi;
const { Box, EventBox, Scrollable, Label } = Widget;

let cachedContent = null;
let wallpaperPaths = [];
let visiblePaths = [];
let isLoading = true;                     

// Read bar position from config
const getBarPosition = () => {
    try {
        const configPath = GLib.get_home_dir() + "/.ags/config.json";
        const config = JSON.parse(Utils.readFile(configPath));
        return config.bar?.position || "top";
    } catch (error) {
        console.error("Error reading config:", error);
        return "top";
    }
};

const WallpaperButton = (path) =>
    Widget.Button({
        child: Box({
            className: "preview-box",
            css: `background-image: url("${path}");`,
        }),
        onClicked: () => {
            Utils.execAsync(
                `sh ${GLib.get_home_dir()}/.config/ags/scripts/color_generation/switchwall.sh "${path}"`,
            );
            App.closeWindow("wallselect");
        },
    });

const getWallpaperPaths = async (directory) => {
    try {
        const files = await Utils.execAsync(
            `find ${GLib.shell_quote(directory)} -type f \\( -iname "*.jpg" -o -iname "*.png" \\)`,
        );
        return files.split("\n").filter((file) => file);
    } catch (error) {
        console.error("Error discovering wallpapers:", error);
        return [];
    }
};

// Debounced scroll event handler
const debouncedScroll = (scroll, delay = 150) => {
    let timeoutId;
    return () => {
        clearTimeout(timeoutId);
        timeoutId = setTimeout(() => {
            const adj = scroll.get_hadjustment();
            const scrollValue = adj.get_value();
            if (scrollValue + adj.get_page_size() >= adj.get_upper() * 0.8) {
                loadMoreWallpapers(scroll);
            }
        }, delay);
    };
};

// Lazy load more wallpapers
const loadMoreWallpapers = (scroll) => {
    if (isLoading || visiblePaths.length >= wallpaperPaths.length) return;
    isLoading = true;

    const loadChunk = 20;
    const newPaths = wallpaperPaths.slice(
        visiblePaths.length,
        visiblePaths.length + loadChunk
    );
    visiblePaths = [...visiblePaths, ...newPaths];

    // Update the scroll content
    scroll.child.children = visiblePaths.map(WallpaperButton);
    isLoading = false;
};

const createContent = async () => {
    if (cachedContent) return cachedContent;

    const wallpaperDir = GLib.build_filenamev([
        GLib.get_home_dir(),
        "Pictures",
        "Wallpapers",
    ]);
    try {
        wallpaperPaths = await getWallpaperPaths(wallpaperDir);

        if (wallpaperPaths.length === 0) {
            return Box({
                className: "wallpaper-placeholder",
                children: [Label({
                    label: "No wallpapers found in ~/Pictures/Wallpapers.",
                    className: "fallback-label",
                })],
            });
        }

        // Load initial batch of wallpapers
        visiblePaths = wallpaperPaths.slice(0, 20);

        const scroll = Scrollable({
            hexpand: true,
            vexpand: false,
            hscroll: "always",
            vscroll: "never",
            child: Box({
                className: "wallpaper-list",
                children: visiblePaths.map(WallpaperButton),
            }),
        });

        // Add debounced scroll handler
        const handleScroll = debouncedScroll(scroll);

        cachedContent = EventBox({
            onScrollUp: () => {
                const adj = scroll.get_hadjustment();
                adj.set_value(adj.get_value() - 100);
                handleScroll();
            },
            onScrollDown: () => {
                const adj = scroll.get_hadjustment();
                adj.set_value(adj.get_value() + 100);
                handleScroll();
            },
            child: scroll,
        });

        return cachedContent;
    } catch (error) {
        console.error("Error loading wallpapers:", error);
        return Box({
            className: "wallpaper-placeholder",
            children: [Label({
                label: "Error loading wallpapers.",
                className: "fallback-label",
            })],
        });
    }
};

createContent();

export default () =>
    Widget.Window({
        name: "wallselect",
        anchor:
            getBarPosition() === "top"
                ? ["top", "left", "right"]
                : ["bottom", "left", "right"],
        visible: false,
        child: Box({
            vertical: true,
            children: [
                EventBox({
                    onPrimaryClick: () => App.closeWindow("wallselect"),
                    onSecondaryClick: () => App.closeWindow("wallselect"),
                    onMiddleClick: () => App.closeWindow("wallselect"),
                }),
                Box({
                    vertical: true,
                    className: "sidebar-right spacing-v-15",
                    children: [
                        Box({
                            vertical: true,
                            className: "sidebar-module",
                            setup: (self) =>
                                self.hook(
                                    App,
                                    async (_, name, visible) => {
                                        if (name === "wallselect" && visible) {
                                            const content =
                                                await createContent();
                                            self.children = [content];
                                        }
                                    },
                                    "window-toggled",
                                ),
                        }),
                    ],
                }),
            ],
        }),
    });

**Comment by PharmaRacist** [comment]
the old one had scrollers but the point is it uses alone 500mb of ram to show 20 pics

**Comment by PharmaRacist** [comment]
if there is a way to cache the already cached images in order not to load them or compress them every time

**Comment by PharmaRacist** [comment]
another thing rn is to set the number of shown wallpapers in config.json and import the variable in this line 
    `    visiblePaths = wallpaperPaths.slice(0, 50);`

**Comment by sh1zicus** [comment]
> another thing rn is to set the number of shown wallpapers in config.json and import the variable in this line
> ` visiblePaths = wallpaperPaths.slice(0, 50);`

I'll try to make thumbnails via vips

**Comment by PharmaRacist** [comment]
finally i got thumbnail generation working so good 😍 the whole ags resource usg is 145mt

**Comment by PharmaRacist** [comment]
im scared of github at this point 😂

**Comment by Pharmaracist** [comment]
`#!/bin/bash

THUMBNAIL_DIR="$HOME/Pictures/Wallpapers/thumbnails"
WALLPAPER_DIR="$HOME/Pictures/Wallpapers"

# Create thumbnail directory if it doesn't exist
mkdir -p "$THUMBNAIL_DIR"

# Generate thumbnails for all wallpapers
find "$WALLPAPER_DIR" -type f \( -iname "*.jpg" -o -iname "*.png" \) | while read -r file; do
    base_name=$(basename "$file")
    thumbnail="$THUMBNAIL_DIR/$base_name"
    if [ ! -f "$thumbnail" ]; then
        magick "$file" -resize 150x90^ -gravity center -extent 150x90 "$thumbnail"
    fi
done
`
make a bash script named ~/.config/ags/scripts/generate_thumbnails.sh sorry 👉👈

**Comment by PharmaRacist** [comment]
`#!/bin/bash

THUMBNAIL_DIR="$HOME/Pictures/Wallpapers/thumbnails"
WALLPAPER_DIR="$HOME/Pictures/Wallpapers"

# Create thumbnail directory if it doesn't exist
mkdir -p "$THUMBNAIL_DIR"

# Generate thumbnails for all wallpapers
find "$WALLPAPER_DIR" -type f \( -iname "*.jpg" -o -iname "*.png" \) | while read -r file; do
    base_name=$(basename "$file")
    thumbnail="$THUMBNAIL_DIR/$base_name"
    if [ ! -f "$thumbnail" ]; then
        magick "$file" -resize 150x90^ -gravity center -extent 150x90 "$thumbnail"
    fi
done`

**Comment by PharmaRacist** [comment]
here `.config/ags/scripts/generate_thumbnails.sh`

**Comment by sh1zicus** [comment]
wow good work 😮

but for some reason scrolling doesn’t work for me in your version, there are still a lot of wallpapers but I can’t scroll further, does it work fine for you?

image

**Comment by PharmaRacist** [comment]
scrolling works good for me and there is also a number of initial loading wallpapers in main.js you can increase the threshhold 
idk about scrolling maybe it has something to do with anchors or monitor scalling

**Comment by sh1zicus** [comment]
so many commits 🤯

**Comment by PharmaRacist** [comment]
how do i manage the dots like you cuz im done with github 👉👈

**Comment by sh1zicus** [comment]
> how do i manage the dots like you cuz im done with github 👉👈

I didn't understand the question 

I just make changes to the cloned repository and update the local config via update dev sh

**Comment by PharmaRacist** [comment]
i started working on the new file system and searated clock-battery-utils-resources

**Comment by PharmaRacist** [comment]
also i added new bar mode that actually doesnt conflict with the original end-4 bar

**Comment by PharmaRacist** [comment]
https://github.com/user-attachments/assets/1d1d3097-cc39-44ca-986b-2f3c4aaf91fc

i just want to make kind of a revealer for the battery module when i press it it reveals the percentage and wattage but i dont know where to start

**Comment by PharmaRacist** [comment]
> > how do i manage the dots like you cuz im done with github 👉👈
> 
> I didn't understand the question
> 
> I just make changes to the cloned repository and update the local config via update dev sh

i use stow to make auto symlinks and github-desktop to commit and push i will try yours

**Comment by PharmaRacist** [comment]
> 2024-11-29.14-55-46.mp4
> 
> i just want to make kind of a revealer for the battery module when i press it it reveals the percentage and wattage but i dont know where to start

done

**Comment by sh1zicus** [comment]
image
I'm trying to make a simple chat matrix inside ags

I’ve already found a bunch of problems and possible improvements, but my brain isn’t enough to fix it and I’ll have to torture it all day long, so I’m just messing around with the chat 🙃

**Comment by PharmaRacist** [comment]
give it a chance you will git it 😁

**Pull request closed without merging**
