### PR TITLE
Fix Spaceleft

### PR DESCRIPTION
**Pull request by PharmaRacist**
- added fallback effect of hiding the icon 
- add custom maximum set of characters to wrap

### CODE REVIEW

**Comment by PharmaRacist** [comment]
i hate github only the spaceleft is needed *shit happens*

**Comment by sh1zicus** [comment]
Oh, there's so much, I'll see if I can find needed 👀

**Comment by sh1zicus** [comment]
изображение

I think should remove this bottom output and insert for example media module there.

**Comment by PharmaRacist** [comment]
> изображение
> 
> I think should remove this bottom output and insert for example media module there.

actually the first time i saw that bottom-title it was useless to me if i use media its in music module 
so in my humble opinion i think we should focus on modularity to separate every module to be sort of puzzle config and just control the way and the look of the system through your app

**Comment by PharmaRacist** [comment]
should i close this ?

**Comment by PharmaRacist** [comment]
image
wdy think ?

**Pull request closed without merging**
