### PR TITLE
Gemini Pro Vision Support

### PR DESCRIPTION
**Pull request by PharmaRacist**

### CODE REVIEW

**Comment by PharmaRacist** [comment]
fuck archlinux i updated the system to find out that there is a fucking dumb aquamarine issue fucking my whole setup and now i have to reinstall the whole thing fuck nvidia you and hyprland i will consider moving to fedora tbh

**Comment by sh1zicus** [comment]
> fuck archlinux i updated the system to find out that there is a fucking dumb aquamarine issue fucking my whole setup and now i have to reinstall the whole thing fuck nvidia you and hyprland i will consider moving to fedora tbh

how about nixos?

**Comment by PharmaRacist** [comment]
> > fuck archlinux i updated the system to find out that there is a fucking dumb aquamarine issue fucking my whole setup and now i have to reinstall the whole thing fuck nvidia you and hyprland i will consider moving to fedora tbh
> 
> how about nixos?

i wanted for a long time to try it but i think its so much hassle do u use it ?

**Comment by sh1zicus** [comment]
> > > fuck archlinux i updated the system to find out that there is a fucking dumb aquamarine issue fucking my whole setup and now i have to reinstall the whole thing fuck nvidia you and hyprland i will consider moving to fedora tbh
> > 
> > how about nixos?
> 
> i wanted for a long time to try it but i think its so much hassle do u use it ?

I want to try to put it on the 2nd ssd one of these days for a ride.

**Comment by PharmaRacist** [comment]
i downloaded the iso already 🐸
but why not debian testing kinda godd ?

**Comment by sh1zicus** [comment]
> i downloaded the iso already 🐸
> but why not debian testing kinda godd ?
> 

I hate debian.🙂

**Comment by PharmaRacist** [comment]
oh god fedora ?

**Comment by PharmaRacist** [comment]
did you try my pr ?

**Pull request closed without merging**
