### PR TITLE
add simple pywal support 

### PR DESCRIPTION
**Pull request by PharmaRacist**
- telegram support through wal-telegram
- pywalfox for firefox and zen-browser
- discord theming through discord-pywal  "in veskord"
- enhance random wallpaper by adding gifs  
sry for the commits

### CODE REVIEW

**Comment by sh1zicus** [comment]
the idea is good, but github is a mess again
I haven’t been able to pull out what I need so that the colors work properly

**Comment by PharmaRacist** [comment]
i will make try to make another branch now and pull here

**Comment by sh1zicus** [comment]
https://github.com/user-attachments/assets/a744a51d-5a81-4b46-82d9-68a2b334a407

**Comment by sh1zicus** [comment]
> i will make try to make another branch now and pull here

I think it’s right for forks to create a separate branch for a pull request

**Comment by sh1zicus** [comment]
and AI changes files so that they seem to have been written anew, changes cannot be tracked 🙃

**Comment by PharmaRacist** [comment]
the issue is u have 2 pywal instances working on foot 
try to disable the term colors from applycolor.sh

**Comment by PharmaRacist** [comment]
> and AI changes files so that they seem to have been written anew, changes cannot be tracked 🙃

jus ctrl+c Ctrl+v all day 🙂

**Comment by sh1zicus** [comment]
> > and AI changes files so that they seem to have been written anew, changes cannot be tracked 🙃
> 
> jus ctrl+c Ctrl+v all day 🙂


https://github.com/user-attachments/assets/d063f544-5ca4-40a8-a087-01a2ac02d6b9

programming is so hard 😔

**Pull request closed without merging**
