### PR TITLE
pywal theming 🪩

### PR DESCRIPTION
**Pull request by PharmaRacist**
- Discord theming "vesktop" - pywal-discord
- zen-browser and any firefox  theming - pywalfox
- telegram theming - wal-telegram or walogram i forgot 🧑‍🦽
- implementing GIF random wallpapers support
- added spotify theming pywal-spicetify you can change the theme thats using through switchwall.sh

### CODE REVIEW

**Comment by sh1zicus** [comment]
https://github.com/user-attachments/assets/28de621c-8167-4a7e-a05c-c5ff791cfcb5

The colors are very sharp and bright, is this how it was intended? At first the correct ones are generated, then after half a second it changes to sharp ones, is it the same with you?

**Comment by sh1zicus** [comment]
изображение
does not change colors in the open foot terminal, but when the terminal is opened again, the colors are correct

**Comment by PharmaRacist** [comment]
this happens because of the original colorgeneration script apply colors on foot also pywal16 does so you need to select one to be applied simply if u use kitty the problem is solved but you can disable term color generation in colorgen.sh script

**Comment by PharmaRacist** [comment]
i will make a work around and update this pull

**Comment by PharmaRacist** [comment]
try now im working on spicetify 👉👈
*this is my first time using pywal* execuse my dumbness

**Comment by PharmaRacist** [comment]
im amazed for the capabilities of pywal i have spent the last 3 hours matching most of my apps to pywal 😁
i dhould find a life

**Comment by PharmaRacist** [comment]
> try now im working on spicetify 👉👈 _this is my first time using pywal_ execuse my dumbness

done
and obsidian

**Comment by sh1zicus** [comment]
https://github.com/user-attachments/assets/db7b1368-3871-4098-a282-7f9655059e54

The animation for changing some wallpapers is broken, I'll try to do something

**Comment by sh1zicus** [comment]
why do you use kitty why is foot not suitable?

**Comment by PharmaRacist** [comment]
im used to the kitty.conf file ihave used it alot

**Pull request merged**
