### PR TITLE
Giving The Bar Some Love 

### PR DESCRIPTION
**Pull request by PharmaRacist**
- new bar modes 
- new file system for the bar modules 
- new bar mechanism to create bars based on index.js that contain bar modes
- easy , modular and more customizable bar
- added some more modules 
- new cava module 🎶

-i need help in the async mechanism to fix window title since i dont really know much about it-      fixed that  
and a function that spawns bar top right/left corners with specific bar modes and kill them in the rest  

Mode 6
Mode 4
Mode 7
f0ba-412d-b801-f3c73916a059)
Mode 5
Mode 1
Mode 2
Mode 3

### CODE REVIEW

**Comment by PharmaRacist** [comment]
yummy 😋
https://github.com/user-attachments/assets/6ec47358-c04c-484a-9701-d9cbeec454a7

**Comment by nichroot** [comment]
yo bro can you help me add this? i tried many ways like sh1zicus told in the other threads, but it doesn't work and throws up a hyprland error

**Comment by PharmaRacist** [comment]
i added more better stuff go to my repo clone it then copy the .config/ags to your .config directory restart ags and tell me what you get maybe you will need to install some packakages but nothing serious

**Comment by nichroot** [comment]
> i added more better stuff go to my repo clone it then copy the .config/ags to your .config directory restart ags and tell me what you get maybe you will need to install some packakages but nothing serious

it showed me the ags error  "Update your user options, One or more config options don't exist", rest eveything works okay and also the adhan timer is reallyy cool, real good work on that!!

**Comment by PharmaRacist** [comment]
can you use my .ags/config.json and the useroption.default.json

**Comment by nichroot** [comment]
also when i updated it with your update script like sh1zicus said, the hyprland config was messed up, it threw a bit errors, can you check on that?

**Comment by PharmaRacist** [comment]
if you are on hyprland 46 it will cuz they changed sth with the colors can you send the terminal log

**Comment by nichroot** [comment]
> can you use my .ags/config.json and the useroption.default.json

hmm.. wheres your .ags located?

**Comment by PharmaRacist** [comment]
at the home directory it should be there

**Comment by nichroot** [comment]
> if you are on hyprland 46 it will cuz they changed sth with the colors can you send the terminal log

ah i think i am on the latest, i'll send the logs rn

**Comment by PharmaRacist** [comment]
if its not jus copy  the content of the useroptionsdefault

**Comment by PharmaRacist** [comment]
u can switch on the ags-tweaksv2 branch cuz maybe maybe thats cuz im working on new features again 🙄

**Comment by nichroot** [comment]
> if its not jus copy the content of the useroptionsdefault

where's useroptionsdefault now 😭

**Comment by PharmaRacist** [comment]
its in ~/.config/ags/modules/.configuration/

**Comment by PharmaRacist** [comment]
did you manage to get it working ?

**Comment by nichroot** [comment]
nope, it just showed another error.. sorry for the late reply btw, there was a power outage, i'll send you the hyprland log rn.. also is there any reason you haven't updated hyprland?

**Comment by nichroot** [comment]
ok now the error is gone and the bar and everything works pretty fine, but the functions like the yt download options and stuff just doesnt quite work, you dont need to bother tho, i'll leave with it or go back to sh1zicus defaults

**Comment by PharmaRacist** [comment]
> ok now the error is gone and the bar and everything works pretty fine, but the functions like the yt download options and stuff just doesnt quite work, you dont need to bother tho, i'll leave with it or go back to sh1zicus defaults

the yt downlaoder script lives in .local/bin you can git it from the gjs repo from sh1zicus and paste it there

**Comment by PharmaRacist** [comment]
i changed alot the bar again making extensive changes and other bar approaches and design languages which i cannot make a pr for it can you take a look at my dotfiles and tellme what you think @sh1zicus

**Comment by nichroot** [comment]
bro please make your own install script bro 😭😭 i will help you test and debug it.. i beg you 😭😭

**Comment by PharmaRacist** [comment]
bro istg it doesnt need an install script u just have the dependencies and copy the .config files and .local and maybe .ags if you have any problem pls send me here ill help you cuz im studing medicine and i have exams these days so im sorry for this and ill make one asap ♥️

**Comment by sh1zicus** [comment]
> i changed alot the bar again making extensive changes and other bar approaches and design languages which i cannot make a pr for it can you take a look at my dotfiles and tellme what you think @sh1zicus

there are a lot of private changes, I’ll try to pull something out if I have time.

and i don’t want to make a bunch of variations of the bar, I just want to make it customizable just like everything else that hasn’t been finalized, but I don’t have free time yet

_you have already run too far from me_ 🙂

**Comment by PharmaRacist** [comment]
> bro please make your own install script bro 😭😭 i will help you test and debug it.. i beg you 😭😭

after fucking my setup i will try to install it using steps i gave you or maybe edit the script to use my repo and add the deps i think ive never take a look into the setup script

**Comment by PharmaRacist** [comment]
so i installed it and managed to get it working with installing some packages that i will add to the install script to support my new features/changes also i think about totally adding hyprland plugins baked in my config sth like hyprchroma hyprfocus hyprflux and more

**Comment by PharmaRacist** [comment]
made an install script and i did try it have a look

**Comment by PharmaRacist** [comment]
actually i made an awesome script and fixed that multible sudo stuff

**Comment by PharmaRacist** [comment]
i dont know what im doing but im rebuilding some modules im adding whole obsidian support /sync with todo module and remaking the gemini sidebar to access notes and tasks and edit them also added pdf support 
i have a fuckkiin examm

**Comment by nichroot** [comment]
broo.. really sorry for irritating you, focus on the exams, didn't know that you were actually a med student.. also a big thanks for the script!! will let you know after trying it out 🫶

**Comment by PharmaRacist** [comment]
> broo.. really sorry for irritating you, focus on the exams, didn't know that you were actually a med student.. also a big thanks for the script!! will let you know after trying it out 🫶

not a big deal G love what am doin but im at collage Medical Pharmacy  🐸

**Comment by nichroot** [comment]
still kinda crazy that you can manage doing these two entirely different stuff simultaneously, real inspirational work broii 🫡

**Comment by nichroot** [comment]
also what os do you recommend for the script? plain arch, endeavor or cachy, and what do you use on yours?

**Comment by PharmaRacist** [comment]
> also what os do you recommend for the script? plain arch, endeavor or cachy, and what do you use on yours?

If you were to install it on endeavour or any flavours distros make sure that you uncheck the eos packages for endeavour didn't face any problems but for the precautions and there is like the github repo named eos to arch Linux if you already forgot and installed those packages

**Comment by nichroot** [comment]
alright, what do you use?

**Comment by PharmaRacist** [comment]
yesterday i used eos but unchecked the eos packages firefox and optional packages just cleans install

**Comment by nichroot** [comment]
ah ok i'll do it and let you know how it works when im on laptop tmrw <3

**Comment by nichroot** [comment]
bro btw when i tested the script on my existing cachy install, it did not work.. the script asked for my password and when i typed the password and hit enter, the script just finished itself

**Comment by PharmaRacist** [comment]
does it do this in the auto mode or the prompted mode and did it work with freash install ?

**Comment by PharmaRacist** [comment]
since i completly sync obsidian with the todo sideleft i said why not make better bigger more complex stuff so i decided to make a complete dashboard for the dots to manage the json stuff in config.json "in future" and continue ai chat in it and full todo application/timer and this is the progress 
image

**Comment by PharmaRacist** [comment]
like you are chatting in the sideleft then press a button and you continue the conversation here with wider fiew

**Comment by PharmaRacist** [comment]
image

**Comment by PharmaRacist** [comment]
tell me what yall think ?

**Comment by sh1zicus** [comment]
> alright, what do you use?

I recommend installing cachyos with gnome, ags requires gnome anyway.

**Comment by PharmaRacist** [comment]
image
trying to make this 
image

**Comment by PharmaRacist** [comment]
how is the experience going on nix ?

**Comment by sh1zicus** [comment]
> how is the experience going on nix ?
> 

very long installation, already 2nd attempt, 1 gave en error 😠

**Comment by PharmaRacist** [comment]
im not happy on fedora too but i managed to get it working rpm is shitty but the performance is very good ags uses much less resources here

**Comment by PharmaRacist** [comment]
ill stay on arch fuck arch 😔

**Comment by PharmaRacist** [comment]
so i managed to use that papirus-folders and made a bash script for color picking logic since it only accepts strings and predefined colors do you need this in a PR ?

**Comment by sh1zicus** [comment]
> so i managed to use that papirus-folders and made a bash script for color picking logic since it only accepts strings and predefined colors do you need this in a PR ?

I don't need it yet, I'm fully loaded.

**Pull request closed without merging**
